/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const selectOuterWrapper: string;
const labelWrapper: string;
const label: string;
const requiredLabel: string;
const select: string;
const invalid: string;
const errorMessage: string;
const selectContainer: string;
const menu: string;
const customChevronWrapper: string;

export {
	selectOuterWrapper,
	labelWrapper,
	label,
	requiredLabel,
	select,
	invalid,
	errorMessage,
	selectContainer,
	menu,
	customChevronWrapper
};

export default {
	selectOuterWrapper,
	labelWrapper,
	label,
	requiredLabel,
	select,
	invalid,
	errorMessage,
	selectContainer,
	menu,
	customChevronWrapper
};
