/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const form: string;
const formHeader: string;
const helperText: string;
const formContent: string;
const innerContent: string;
const actionBar: string;

export { form, formHeader, helperText, formContent, innerContent, actionBar };

export default {
  form,
  formHeader,
  helperText,
  formContent,
  innerContent,
  actionBar,
};
