/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const dataTableRow: string;
const disabled: string;
const selected: string;
const ssnContainer: string;
const dragging: string;
const draggable: string;
const expanded: string;
const collapsibleRow: string;
const collapsibleContent: string;
const base: string;
const condensed: string;
const dataTableCell: string;
const dropdownTrigger: string;
const collapsibleContentRow: string;
const clickable: string;
const collapsibleContentWrapper: string;
const collapsibleContentInner: string;
const expandColumn: string;
const expandButton: string;
const expandIcon: string;

export {
	dataTableRow,
	disabled,
	selected,
	ssnContainer,
	dragging,
	draggable,
	expanded,
	collapsibleRow,
	collapsibleContent,
	base,
	condensed,
	dataTableCell,
	dropdownTrigger,
	collapsibleContentRow,
	clickable,
	collapsibleContentWrapper,
	collapsibleContentInner,
	expandColumn,
	expandButton,
	expandIcon
};

export default {
	dataTableRow,
	disabled,
	selected,
	ssnContainer,
	dragging,
	draggable,
	expanded,
	collapsibleRow,
	collapsibleContent,
	base,
	condensed,
	dataTableCell,
	dropdownTrigger,
	collapsibleContentRow,
	clickable,
	collapsibleContentWrapper,
	collapsibleContentInner,
	expandColumn,
	expandButton,
	expandIcon
};
