/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const modalTitle: string;
const modalBody: string;
const modalFooter: string;
const customFooter: string;
const defaultActions: string;
const secondaryActions: string;
const modalOverlay: string;
const overlayShow: string;
const small: string;
const medium: string;
const large: string;
const modal: string;
const contentShow: string;
const modalClose: string;
const ReactCrop__childWrapper: string;

export {
  modalTitle,
  modalBody,
  modalFooter,
  customFooter,
  defaultActions,
  secondaryActions,
  modalOverlay,
  overlayShow,
  small,
  medium,
  large,
  modal,
  contentShow,
  modalClose,
  ReactCrop__childWrapper as reactCropChildWrapper,
};

export default {
  modalTitle,
  modalBody,
  modalFooter,
  customFooter,
  defaultActions,
  secondaryActions,
  modalOverlay,
  overlayShow,
  small,
  medium,
  large,
  modal,
  contentShow,
  modalClose,
  reactCropChildWrapper: ReactCrop__childWrapper,
};
