/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const wrapper: string;
const menu: string;

export { wrapper, menu };

export default {
  wrapper,
  menu,
};
