/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const switchRoot: string;
const switchThumb: string;
const switchWrapper: string;
const switchBase: string;
const switchLabel: string;
const labelWrapper: string;
const labelRight: string;
const labelLeft: string;
const label: string;
const labelInline: string;
const requiredLabel: string;
const labelDisabled: string;
const visuallyHidden: string;

export {
	switchRoot,
	switchThumb,
	switchWrapper,
	switchBase,
	switchLabel,
	labelWrapper,
	labelRight,
	labelLeft,
	label,
	labelInline,
	requiredLabel,
	labelDisabled,
	visuallyHidden
};

export default {
	switchRoot,
	switchThumb,
	switchWrapper,
	switchBase,
	switchLabel,
	labelWrapper,
	labelRight,
	labelLeft,
	label,
	labelInline,
	requiredLabel,
	labelDisabled,
	visuallyHidden
};
