/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const textArea: string;
const label: string;
const requiredLabel: string;
const labelDisabled: string;
const formItem: string;
const textAreaWrapper: string;
const textAreaFieldOuterWrapper: string;
const textAreaFieldWrapper: string;
const contentWrapper: string;
const textAreaLabelWrapper: string;
const textAreaLabelCounter: string;
const textAreaLabelHelperWrapper: string;
const textAreaWarning: string;
const textAreaInvalid: string;
const textAreaSuccess: string;
const formCounterText: string;
const formCounterTextDisabled: string;
const formHelperText: string;
const formHelperTextDisabled: string;
const errorText: string;
const formRequirement: string;
const textAreaFieldWrapperWarning: string;
const textAreaFieldWrapperInvalid: string;
const textAreaFieldWrapperSuccess: string;
const successIcon: string;
const warningIcon: string;
const errorIcon: string;
const textInputFieldWrapperSuccess: string;
const visuallyHidden: string;

export {
	textArea,
	label,
	requiredLabel,
	labelDisabled,
	formItem,
	textAreaWrapper,
	textAreaFieldOuterWrapper,
	textAreaFieldWrapper,
	contentWrapper,
	textAreaLabelWrapper,
	textAreaLabelCounter,
	textAreaLabelHelperWrapper,
	textAreaWarning,
	textAreaInvalid,
	textAreaSuccess,
	formCounterText,
	formCounterTextDisabled,
	formHelperText,
	formHelperTextDisabled,
	errorText,
	formRequirement,
	textAreaFieldWrapperWarning,
	textAreaFieldWrapperInvalid,
	textAreaFieldWrapperSuccess,
	successIcon,
	warningIcon,
	errorIcon,
	textInputFieldWrapperSuccess,
	visuallyHidden
};

export default {
	textArea,
	label,
	requiredLabel,
	labelDisabled,
	formItem,
	textAreaWrapper,
	textAreaFieldOuterWrapper,
	textAreaFieldWrapper,
	contentWrapper,
	textAreaLabelWrapper,
	textAreaLabelCounter,
	textAreaLabelHelperWrapper,
	textAreaWarning,
	textAreaInvalid,
	textAreaSuccess,
	formCounterText,
	formCounterTextDisabled,
	formHelperText,
	formHelperTextDisabled,
	errorText,
	formRequirement,
	textAreaFieldWrapperWarning,
	textAreaFieldWrapperInvalid,
	textAreaFieldWrapperSuccess,
	successIcon,
	warningIcon,
	errorIcon,
	textInputFieldWrapperSuccess,
	visuallyHidden
};
