/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const successMessageContainer: string;
const errorMessageContainer: string;
const iconContainer: string;
const dismissButton: string;

export {
	successMessageContainer,
	errorMessageContainer,
	iconContainer,
	dismissButton
};

export default {
	successMessageContainer,
	errorMessageContainer,
	iconContainer,
	dismissButton
};
