/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const base: string;
const row: string;
const layoutVariants1Column: string;
const layoutVariants2Column: string;
const layoutVariants3Column: string;
const layoutVariants4Column: string;
const formWrapper: string;
const wrapperVariants: string;
const wrapperVariantsBase: string;
const wrapperVariantsPanel: string;

export {
	base,
	row,
	layoutVariants1Column,
	layoutVariants2Column,
	layoutVariants3Column,
	layoutVariants4Column,
	formWrapper,
	wrapperVariants,
	wrapperVariantsBase,
	wrapperVariantsPanel
};

export default {
	base,
	row,
	layoutVariants1Column,
	layoutVariants2Column,
	layoutVariants3Column,
	layoutVariants4Column,
	formWrapper,
	wrapperVariants,
	wrapperVariantsBase,
	wrapperVariantsPanel
};
