/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const mainContainer: string;
const content: string;
const link: string;
const subheading: string;
const linkItem: string;
const linkList: string;

export {
	mainContainer,
	content,
	link,
	subheading,
	linkItem,
	linkList
};

export default {
	mainContainer,
	content,
	link,
	subheading,
	linkItem,
	linkList
};
