/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const baseSectionAlertStyle: string;
const wrapper: string;
const sectionAlertMessageHeading: string;
const heading1: string;
const heading2: string;
const layout1: string;
const layout2: string;
const sectionAlertMessage: string;
const sectionAlertMessageLink: string;
const sectionAlertAdditionalMessage: string;
const sectionAlertIcon: string;
const warning: string;
const success: string;
const info: string;
const error: string;
const global: string;

export {
  baseSectionAlertStyle,
  wrapper,
  sectionAlertMessageHeading,
  heading1,
  heading2,
  layout1,
  layout2,
  sectionAlertMessage,
  sectionAlertMessageLink,
  sectionAlertAdditionalMessage,
  sectionAlertIcon,
  warning,
  success,
  info,
  error,
  global,
};

export default {
  baseSectionAlertStyle,
  wrapper,
  sectionAlertMessageHeading,
  heading1,
  heading2,
  layout1,
  layout2,
  sectionAlertMessage,
  sectionAlertMessageLink,
  sectionAlertAdditionalMessage,
  sectionAlertIcon,
  warning,
  success,
  info,
  error,
  global,
};
