/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const divider: string;
const thin: string;
const medium: string;
const thick: string;
const vertical: string;
const horizontal: string;

export {
	divider,
	thin,
	medium,
	thick,
	vertical,
	horizontal
};

export default {
	divider,
	thin,
	medium,
	thick,
	vertical,
	horizontal
};
