/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const tabGroupContainer: string;
const tabGroup: string;
const tabHeaders: string;
const tab: string;
const active: string;
const tabBar: string;
const tabScroller: string;
const tabScrollerScroll: string;
const tabScrollerScrollArea: string;
const tabScrollerScrollContent: string;
const tabScrollArrows: string;
const tabList: string;
const tabBorder: string;

export {
  tabGroupContainer,
  tabGroup,
  tabHeaders,
  tab,
  active,
  tabBar,
  tabScroller,
  tabScrollerScroll,
  tabScrollerScrollArea,
  tabScrollerScrollContent,
  tabScrollArrows,
  tabList,
  tabBorder,
};

export default {
  tabGroupContainer,
  tabGroup,
  tabHeaders,
  tab,
  active,
  tabBar,
  tabScroller,
  tabScrollerScroll,
  tabScrollerScrollArea,
  tabScrollerScrollContent,
  tabScrollArrows,
  tabList,
  tabBorder,
};
