/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const root: string;
const months: string;
const month: string;
const caption: string;
const captionLabel: string;
const navButton: string;
const nav: string;
const navButtonPrevious: string;
const navButtonNext: string;
const table: string;
const headRow: string;
const headCell: string;
const row: string;
const cell: string;
const dayButton: string;
const daySelected: string;
const dayToday: string;
const dayOutside: string;
const dayDisabled: string;
const dayRangeMiddle: string;
const dayHidden: string;
const dayRangeStart: string;
const dayRangeEnd: string;
const weekNumber: string;
const dropdown: string;

export {
  root,
  months,
  month,
  caption,
  captionLabel,
  navButton,
  nav,
  navButtonPrevious,
  navButtonNext,
  table,
  headRow,
  headCell,
  row,
  cell,
  dayButton,
  daySelected,
  dayToday,
  dayOutside,
  dayDisabled,
  dayRangeMiddle,
  dayHidden,
  dayRangeStart,
  dayRangeEnd,
  weekNumber,
  dropdown,
};

export default {
  root,
  months,
  month,
  caption,
  captionLabel,
  navButton,
  nav,
  navButtonPrevious,
  navButtonNext,
  table,
  headRow,
  headCell,
  row,
  cell,
  dayButton,
  daySelected,
  dayToday,
  dayOutside,
  dayDisabled,
  dayRangeMiddle,
  dayHidden,
  dayRangeStart,
  dayRangeEnd,
  weekNumber,
  dropdown,
};
