/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const wrapper: string;
const innerWrapper: string;
const truncate: string;
const popover: string;
const textInput: string;

export {
	container,
	wrapper,
	innerWrapper,
	truncate,
	popover,
	textInput
};

export default {
	container,
	wrapper,
	innerWrapper,
	truncate,
	popover,
	textInput
};
