/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const popoverContent: string;
const popoverIn: string;
const popoverOut: string;

export {
	popoverContent,
	popoverIn,
	popoverOut
};

export default {
	popoverContent,
	popoverIn,
	popoverOut
};
