/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const selectOuterWrapper: string;
const selectWrapper: string;
const label: string;
const labelWrapper: string;
const requiredLabel: string;
const disabledLabel: string;
const selectLabelWrapper: string;
const trigger: string;
const focused: string;
const triggerIcon: string;
const value: string;
const menu: string;
const menuItemContent: string;
const item: string;
const selected: string;
const disabled: string;
const iconSelected: string;
const itemIndicator: string;
const highlighted: string;
const invalid: string;
const errorMessage: string;
const visuallyHidden: string;
const paginationVariant: string;

export {
  selectOuterWrapper,
  selectWrapper,
  label,
  labelWrapper,
  requiredLabel,
  disabledLabel,
  selectLabelWrapper,
  trigger,
  focused,
  triggerIcon,
  value,
  menu,
  menuItemContent,
  item,
  selected,
  disabled,
  iconSelected,
  itemIndicator,
  highlighted,
  invalid,
  errorMessage,
  visuallyHidden,
  paginationVariant,
};

export default {
  selectOuterWrapper,
  selectWrapper,
  label,
  labelWrapper,
  requiredLabel,
  disabledLabel,
  selectLabelWrapper,
  trigger,
  focused,
  triggerIcon,
  value,
  menu,
  menuItemContent,
  item,
  selected,
  disabled,
  iconSelected,
  itemIndicator,
  highlighted,
  invalid,
  errorMessage,
  visuallyHidden,
  paginationVariant,
};
