/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const badge: string;
const square: string;
const bevel: string;
const round: string;
const base: string;
const info: string;
const success: string;
const accent: string;
const warning: string;
const error: string;
const iconContainer: string;

export {
	badge,
	square,
	bevel,
	round,
	base,
	info,
	success,
	accent,
	warning,
	error,
	iconContainer
};

export default {
	badge,
	square,
	bevel,
	round,
	base,
	info,
	success,
	accent,
	warning,
	error,
	iconContainer
};
