/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const panel: string;
const base: string;
const none: string;
const panelHeader: string;
const panelHeaderText: string;
const panelHeaderIcon: string;
const panelContent: string;
const panelFooter: string;
const footerDivider: string;
const errorContainer: string;

export {
  panel,
  base,
  none,
  panelHeader,
  panelHeaderText,
  panelHeaderIcon,
  panelContent,
  panelFooter,
  footerDivider,
  errorContainer,
};

export default {
  panel,
  base,
  none,
  panelHeader,
  panelHeaderText,
  panelHeaderIcon,
  panelContent,
  panelFooter,
  footerDivider,
  errorContainer,
};
