/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const accordionContainer: string;
const dark: string;
const accordionItem: string;
const accordionHeading: string;
const accordionHeader: string;
const accordionContent: string;
const accordionContentOpen: string;
const accordionContentClosed: string;
const accordionContentInner: string;
const accordionDescription: string;
const accordionTitle: string;
const accordionTrigger: string;
const accordionChevron: string;
const accordionContextMenu: string;

export {
	accordionContainer,
	dark,
	accordionItem,
	accordionHeading,
	accordionHeader,
	accordionContent,
	accordionContentOpen,
	accordionContentClosed,
	accordionContentInner,
	accordionDescription,
	accordionTitle,
	accordionTrigger,
	accordionChevron,
	accordionContextMenu
};

export default {
	accordionContainer,
	dark,
	accordionItem,
	accordionHeading,
	accordionHeader,
	accordionContent,
	accordionContentOpen,
	accordionContentClosed,
	accordionContentInner,
	accordionDescription,
	accordionTitle,
	accordionTrigger,
	accordionChevron,
	accordionContextMenu
};
