/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const formHelperTextDisabled: string;
const formHelperText: string;

export { formHelperTextDisabled, formHelperText };

export default {
  formHelperTextDisabled,
  formHelperText,
};
