/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const chip: string;
const chipAvatar: string;
const customIconWrapper: string;
const label: string;
const iconWrapper: string;
const deleteIcon: string;
const active: string;
const base: string;
const outline: string;
const primary: string;

export { chip, chipAvatar, customIconWrapper, label, iconWrapper, deleteIcon, active, base, outline, primary };

export default {
  chip,
  chipAvatar,
  customIconWrapper,
  label,
  iconWrapper,
  deleteIcon,
  active,
  base,
  outline,
  primary,
};
