/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const sidebar: string;
const collapsed: string;
const base: string;
const compact: string;
const minimal: string;
const sidebarHeader: string;
const withHeaderHidden: string;
const brand: string;
const logoContainer: string;
const logoButton: string;
const sectionHeader: string;
const sectionHeaderCollapsible: string;
const sectionToggleIcon: string;
const sectionContent: string;
const sectionContentAnimated: string;
const sectionContentExpanded: string;
const sidebarContent: string;
const sidebarNav: string;
const navSection: string;
const sidebarSection: string;
const sectionTitle: string;
const sectionContentItems: string;
const navButton: string;
const navActions: string;
const active: string;
const disabled: string;
const iconButton: string;
const navLabel: string;
const navBadge: string;
const navActionsVisible: string;
const sidebarFooter: string;
const cancelIcon: string;
const mainAction: string;
const sidebarMenuTrigger: string;
const sidebarMenuPanel: string;
const sidebarMenuSlideIn: string;
const sidebarMenuPanelSlide: string;
const sidebarMenuSlideOut: string;
const sidebarMenuItem: string;
const sidebarMenuItemIcon: string;
const mobileOpen: string;
const sidebarBackdrop: string;
const visible: string;

export {
  sidebar,
  collapsed,
  base,
  compact,
  minimal,
  sidebarHeader,
  withHeaderHidden,
  brand,
  logoContainer,
  logoButton,
  sectionHeader,
  sectionHeaderCollapsible,
  sectionToggleIcon,
  sectionContent,
  sectionContentAnimated,
  sectionContentExpanded,
  sidebarContent,
  sidebarNav,
  navSection,
  sidebarSection,
  sectionTitle,
  sectionContentItems,
  navButton,
  navActions,
  active,
  disabled,
  iconButton,
  navLabel,
  navBadge,
  navActionsVisible,
  sidebarFooter,
  cancelIcon,
  mainAction,
  sidebarMenuTrigger,
  sidebarMenuPanel,
  sidebarMenuSlideIn,
  sidebarMenuPanelSlide,
  sidebarMenuSlideOut,
  sidebarMenuItem,
  sidebarMenuItemIcon,
  mobileOpen,
  sidebarBackdrop,
  visible,
};

export default {
  sidebar,
  collapsed,
  base,
  compact,
  minimal,
  sidebarHeader,
  withHeaderHidden,
  brand,
  logoContainer,
  logoButton,
  sectionHeader,
  sectionHeaderCollapsible,
  sectionToggleIcon,
  sectionContent,
  sectionContentAnimated,
  sectionContentExpanded,
  sidebarContent,
  sidebarNav,
  navSection,
  sidebarSection,
  sectionTitle,
  sectionContentItems,
  navButton,
  navActions,
  active,
  disabled,
  iconButton,
  navLabel,
  navBadge,
  navActionsVisible,
  sidebarFooter,
  cancelIcon,
  mainAction,
  sidebarMenuTrigger,
  sidebarMenuPanel,
  sidebarMenuSlideIn,
  sidebarMenuPanelSlide,
  sidebarMenuSlideOut,
  sidebarMenuItem,
  sidebarMenuItemIcon,
  mobileOpen,
  sidebarBackdrop,
  visible,
};
