/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const button: string;
const small: string;
const medium: string;
const large: string;
const none: string;
const outline: string;
const filled: string;
const square: string;
const bevel: string;
const round: string;
const base: string;
const primary: string;
const secondary: string;
const tertiary: string;
const accent: string;
const danger: string;
const spinner: string;
const spin: string;
const visuallyHidden: string;

export {
	button,
	small,
	medium,
	large,
	none,
	outline,
	filled,
	square,
	bevel,
	round,
	base,
	primary,
	secondary,
	tertiary,
	accent,
	danger,
	spinner,
	spin,
	visuallyHidden
};

export default {
	button,
	small,
	medium,
	large,
	none,
	outline,
	filled,
	square,
	bevel,
	round,
	base,
	primary,
	secondary,
	tertiary,
	accent,
	danger,
	spinner,
	spin,
	visuallyHidden
};
