/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const popoverTrigger: string;
const popoverContent: string;
const slideDownAndFade: string;
const slideLeftAndFade: string;
const slideUpAndFade: string;
const slideRightAndFade: string;
const popoverArrow: string;
const hideArrow: string;
const popoverClose: string;

export {
  popoverTrigger,
  popoverContent,
  slideDownAndFade,
  slideLeftAndFade,
  slideUpAndFade,
  slideRightAndFade,
  popoverArrow,
  hideArrow,
  popoverClose,
};

export default {
  popoverTrigger,
  popoverContent,
  slideDownAndFade,
  slideLeftAndFade,
  slideUpAndFade,
  slideRightAndFade,
  popoverArrow,
  hideArrow,
  popoverClose,
};
