/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const loader: string;
const spinner: string;
const rotate: string;
const loaderContainer: string;
const staticCircle: string;
const animatedCircle: string;
const dash: string;
const loadingOverlay: string;
const fullScreenOverlay: string;
const loadingOverlayStop: string;
const description: string;

export {
  loader,
  spinner,
  rotate,
  loaderContainer,
  staticCircle,
  animatedCircle,
  dash,
  loadingOverlay,
  fullScreenOverlay,
  loadingOverlayStop,
  description,
};

export default {
  loader,
  spinner,
  rotate,
  loaderContainer,
  staticCircle,
  animatedCircle,
  dash,
  loadingOverlay,
  fullScreenOverlay,
  loadingOverlayStop,
  description,
};
