/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const content: string;

export {
	container,
	content
};

export default {
	container,
	content
};
