/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const drawerContainer: string;
const drawerContent: string;
const closeButton: string;

export { drawerContainer, drawerContent, closeButton };

export default {
  drawerContainer,
  drawerContent,
  closeButton,
};
