/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const titleSection: string;
const actionButtons: string;

export {
	container,
	titleSection,
	actionButtons
};

export default {
	container,
	titleSection,
	actionButtons
};
