/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const tableHead: string;
const checkboxColumn: string;

export {
	tableHead,
	checkboxColumn
};

export default {
	tableHead,
	checkboxColumn
};
