/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const pagination: string;
const paginationWrapper: string;
const pageList: string;
const pageSizeSelect: string;
const selectContainer: string;
const pageNumbers: string;
const activePage: string;
const paginationButton: string;
const pageInfo: string;
const ellipsis: string;

export {
  pagination,
  paginationWrapper,
  pageList,
  pageSizeSelect,
  selectContainer,
  pageNumbers,
  activePage,
  paginationButton,
  pageInfo,
  ellipsis,
};

export default {
  pagination,
  paginationWrapper,
  pageList,
  pageSizeSelect,
  selectContainer,
  pageNumbers,
  activePage,
  paginationButton,
  pageInfo,
  ellipsis,
};
