/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const ssnContainer: string;
const ssnText: string;

export {
	ssnContainer,
	ssnText
};

export default {
	ssnContainer,
	ssnText
};
