/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const containerStatic: string;
const header: string;
const headerTitle: string;
const headerDescription: string;
const stickyHeaderMaxWidth: string;

export { container, containerStatic, header, headerTitle, headerDescription, stickyHeaderMaxWidth };

export default {
  container,
  containerStatic,
  header,
  headerTitle,
  headerDescription,
  stickyHeaderMaxWidth,
};
