/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const tableContainer: string;
const none: string;
const rounded: string;
const dataTable: string;
const pagination: string;
const content: string;
const checkboxColumn: string;
const dataTableCell: string;
const sort: string;
const sortButton: string;
const dataTableHeader: string;
const sortIcon: string;
const emptyMessageContainer: string;
const emptyMessage: string;
const emptyCell: string;
const dragOver: string;
const dragging: string;
const loaderCell: string;
const errorCell: string;
const errorMessageContainer: string;
const errorMessageContent: string;
const errorIcon: string;
const errorMessage: string;
const dataTableRow: string;
const selected: string;
const disabled: string;
const dropdownTrigger: string;

export {
  tableContainer,
  none,
  rounded,
  dataTable,
  pagination,
  content,
  checkboxColumn,
  dataTableCell,
  sort,
  sortButton,
  dataTableHeader,
  sortIcon,
  emptyMessageContainer,
  emptyMessage,
  emptyCell,
  dragOver,
  dragging,
  loaderCell,
  errorCell,
  errorMessageContainer,
  errorMessageContent,
  errorIcon,
  errorMessage,
  dataTableRow,
  selected,
  disabled,
  dropdownTrigger,
};

export default {
  tableContainer,
  none,
  rounded,
  dataTable,
  pagination,
  content,
  checkboxColumn,
  dataTableCell,
  sort,
  sortButton,
  dataTableHeader,
  sortIcon,
  emptyMessageContainer,
  emptyMessage,
  emptyCell,
  dragOver,
  dragging,
  loaderCell,
  errorCell,
  errorMessageContainer,
  errorMessageContent,
  errorIcon,
  errorMessage,
  dataTableRow,
  selected,
  disabled,
  dropdownTrigger,
};
