/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const skeletonTable: string;
const skeletonHeader: string;
const skeletonRow: string;
const skeletonCell: string;
const pulse: string;
const header: string;
const headerText: string;
const textContent: string;
const primaryText: string;
const secondaryText: string;
const avatarCell: string;
const avatar: string;
const avatarText: string;
const badge: string;
const numberText: string;
const dateText: string;

export {
  skeletonTable,
  skeletonHeader,
  skeletonRow,
  skeletonCell,
  pulse,
  header,
  headerText,
  textContent,
  primaryText,
  secondaryText,
  avatarCell,
  avatar,
  avatarText,
  badge,
  numberText,
  dateText,
};

export default {
  skeletonTable,
  skeletonHeader,
  skeletonRow,
  skeletonCell,
  pulse,
  header,
  headerText,
  textContent,
  primaryText,
  secondaryText,
  avatarCell,
  avatar,
  avatarText,
  badge,
  numberText,
  dateText,
};
