/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const dialog: string;
const contentShow: string;
const dialogTitle: string;
const dialogBody: string;
const dialogFooter: string;
const dialogFooterContent: string;
const dialogOverlay: string;
const overlayShow: string;
const small: string;
const medium: string;
const large: string;
const dialogClose: string;

export {
	dialog,
	contentShow,
	dialogTitle,
	dialogBody,
	dialogFooter,
	dialogFooterContent,
	dialogOverlay,
	overlayShow,
	small,
	medium,
	large,
	dialogClose
};

export default {
	dialog,
	contentShow,
	dialogTitle,
	dialogBody,
	dialogFooter,
	dialogFooterContent,
	dialogOverlay,
	overlayShow,
	small,
	medium,
	large,
	dialogClose
};
