/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const wrapper: string;
const svgContainer: string;
const circleWrapper: string;
const circle: string;
const active: string;
const shadowPulse: string;
const circlePulse: string;
const disabled: string;
const statusText: string;
const textContainer: string;
const statusTextContent: string;
const statusDots: string;
const initial: string;
const entering: string;
const current: string;
const exiting: string;
const progressBarContainer: string;
const progressBar: string;
const indeterminateProgress: string;

export {
	container,
	wrapper,
	svgContainer,
	circleWrapper,
	circle,
	active,
	shadowPulse,
	circlePulse,
	disabled,
	statusText,
	textContainer,
	statusTextContent,
	statusDots,
	initial,
	entering,
	current,
	exiting,
	progressBarContainer,
	progressBar,
	indeterminateProgress
};

export default {
	container,
	wrapper,
	svgContainer,
	circleWrapper,
	circle,
	active,
	shadowPulse,
	circlePulse,
	disabled,
	statusText,
	textContainer,
	statusTextContent,
	statusDots,
	initial,
	entering,
	current,
	exiting,
	progressBarContainer,
	progressBar,
	indeterminateProgress
};
