/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const vertical: string;
const horizontal: string;
const radioButtonWrapper: string;
const visuallyHidden: string;
const radioButtonLabel: string;
const radioButton: string;
const radioButtonAppearance: string;
const formItem: string;
const radioButtonGroup: string;
const radioButtonGroupContent: string;
const layoutHorizontal: string;
const layoutVertical: string;
const groupLabel: string;
const radioButtonGroupInvalid: string;
const radioButtonGroupWarning: string;
const radioButtonGroupReadonly: string;
const radioButtonInvalidIcon: string;
const radioButtonInvalidIconWarning: string;
const radioButtonValidationMsg: string;
const formRequirement: string;
const formHelperText: string;

export {
	vertical,
	horizontal,
	radioButtonWrapper,
	visuallyHidden,
	radioButtonLabel,
	radioButton,
	radioButtonAppearance,
	formItem,
	radioButtonGroup,
	radioButtonGroupContent,
	layoutHorizontal,
	layoutVertical,
	groupLabel,
	radioButtonGroupInvalid,
	radioButtonGroupWarning,
	radioButtonGroupReadonly,
	radioButtonInvalidIcon,
	radioButtonInvalidIconWarning,
	radioButtonValidationMsg,
	formRequirement,
	formHelperText
};

export default {
	vertical,
	horizontal,
	radioButtonWrapper,
	visuallyHidden,
	radioButtonLabel,
	radioButton,
	radioButtonAppearance,
	formItem,
	radioButtonGroup,
	radioButtonGroupContent,
	layoutHorizontal,
	layoutVertical,
	groupLabel,
	radioButtonGroupInvalid,
	radioButtonGroupWarning,
	radioButtonGroupReadonly,
	radioButtonInvalidIcon,
	radioButtonInvalidIconWarning,
	radioButtonValidationMsg,
	formRequirement,
	formHelperText
};
