/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const iconContainer: string;
const icon: string;
const sizeSmall: string;
const sizeDefault: string;
const sizeLarge: string;
const colorDefault: string;
const colorPrimary: string;
const colorSecondary: string;
const colorTertiary: string;
const colorAccent: string;
const colorDisabled: string;
const colorInfo: string;
const colorSuccess: string;
const colorWarning: string;
const colorError: string;

export {
  iconContainer,
  icon,
  sizeSmall,
  sizeDefault,
  sizeLarge,
  colorDefault,
  colorPrimary,
  colorSecondary,
  colorTertiary,
  colorAccent,
  colorDisabled,
  colorInfo,
  colorSuccess,
  colorWarning,
  colorError,
};

export default {
  iconContainer,
  icon,
  sizeSmall,
  sizeDefault,
  sizeLarge,
  colorDefault,
  colorPrimary,
  colorSecondary,
  colorTertiary,
  colorAccent,
  colorDisabled,
  colorInfo,
  colorSuccess,
  colorWarning,
  colorError,
};
