/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const trigger: string;
const content: string;
const arrow: string;
const fadeOut: string;
const slideDown: string;
const slideLeft: string;
const slideUp: string;
const slideRight: string;
const textAlignLeft: string;
const textAlignCenter: string;
const textAlignRight: string;

export {
	trigger,
	content,
	arrow,
	fadeOut,
	slideDown,
	slideLeft,
	slideUp,
	slideRight,
	textAlignLeft,
	textAlignCenter,
	textAlignRight
};

export default {
	trigger,
	content,
	arrow,
	fadeOut,
	slideDown,
	slideLeft,
	slideUp,
	slideRight,
	textAlignLeft,
	textAlignCenter,
	textAlignRight
};
