/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const chip: string;
const base: string;
const success: string;
const error: string;
const infoWrapper: string;
const fileIconWrapper: string;
const fileInfo: string;
const fileName: string;
const fileMetaData: string;
const fileTypeIcon: string;
const actionButtons: string;
const retryButton: string;
const removeButton: string;
const loading: string;

export {
	chip,
	base,
	success,
	error,
	infoWrapper,
	fileIconWrapper,
	fileInfo,
	fileName,
	fileMetaData,
	fileTypeIcon,
	actionButtons,
	retryButton,
	removeButton,
	loading
};

export default {
	chip,
	base,
	success,
	error,
	infoWrapper,
	fileIconWrapper,
	fileInfo,
	fileName,
	fileMetaData,
	fileTypeIcon,
	actionButtons,
	retryButton,
	removeButton,
	loading
};
