/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const toggleGroup: string;
const toggleItem: string;

export {
	toggleGroup,
	toggleItem
};

export default {
	toggleGroup,
	toggleItem
};
