/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const avatar: string;
const avatarPlaceholder: string;
const placeholderText: string;
const sm: string;
const md: string;
const lg: string;
const xl: string;

export {
	avatar,
	avatarPlaceholder,
	placeholderText,
	sm,
	md,
	lg,
	xl
};

export default {
	avatar,
	avatarPlaceholder,
	placeholderText,
	sm,
	md,
	lg,
	xl
};
