/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const validationMsg: string;
const formRequirementInvalid: string;
const formRequirementWarning: string;
const formRequirementSuccess: string;

export {
	validationMsg,
	formRequirementInvalid,
	formRequirementWarning,
	formRequirementSuccess
};

export default {
	validationMsg,
	formRequirementInvalid,
	formRequirementWarning,
	formRequirementSuccess
};
