/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const main: string;
const mainList: string;
const link: string;

export { main, mainList, link };

export default {
  main,
  mainList,
  link,
};
