/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const checkbox: string;
const disabled: string;
const indeterminate: string;
const checkboxWrapper: string;
const label: string;
const visuallyHidden: string;
const requiredLabel: string;

export {
	checkbox,
	disabled,
	indeterminate,
	checkboxWrapper,
	label,
	visuallyHidden,
	requiredLabel
};

export default {
	checkbox,
	disabled,
	indeterminate,
	checkboxWrapper,
	label,
	visuallyHidden,
	requiredLabel
};
