/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const textInput: string;
const label: string;
const requiredLabel: string;
const labelDisabled: string;
const formItem: string;
const textInputWrapper: string;
const textInputFieldOuterWrapper: string;
const textInputFieldWrapper: string;
const textInputLabelWrapper: string;
const textInputLabelCounter: string;
const textInputLabelHelperWrapper: string;
const textInputWrapperInlineInvalid: string;
const textInputWrapperInline: string;
const textInputFieldOuterWrapperInline: string;
const formHelperTextInline: string;
const labelInline: string;
const textInputWarning: string;
const textInputInvalid: string;
const textInputSuccess: string;
const formHelperText: string;
const formHelperTextDisabled: string;
const errorText: string;
const formRequirement: string;
const textInputFieldWrapperWarning: string;
const textInputFieldWrapperInvalid: string;
const textInputFieldWrapperSuccess: string;
const successIcon: string;
const warningIcon: string;
const errorIcon: string;
const textInputCounterAlert: string;
const visuallyHidden: string;
const autofill: string;

export {
  textInput,
  label,
  requiredLabel,
  labelDisabled,
  formItem,
  textInputWrapper,
  textInputFieldOuterWrapper,
  textInputFieldWrapper,
  textInputLabelWrapper,
  textInputLabelCounter,
  textInputLabelHelperWrapper,
  textInputWrapperInlineInvalid,
  textInputWrapperInline,
  textInputFieldOuterWrapperInline,
  formHelperTextInline,
  labelInline,
  textInputWarning,
  textInputInvalid,
  textInputSuccess,
  formHelperText,
  formHelperTextDisabled,
  errorText,
  formRequirement,
  textInputFieldWrapperWarning,
  textInputFieldWrapperInvalid,
  textInputFieldWrapperSuccess,
  successIcon,
  warningIcon,
  errorIcon,
  textInputCounterAlert,
  visuallyHidden,
  autofill,
};

export default {
  textInput,
  label,
  requiredLabel,
  labelDisabled,
  formItem,
  textInputWrapper,
  textInputFieldOuterWrapper,
  textInputFieldWrapper,
  textInputLabelWrapper,
  textInputLabelCounter,
  textInputLabelHelperWrapper,
  textInputWrapperInlineInvalid,
  textInputWrapperInline,
  textInputFieldOuterWrapperInline,
  formHelperTextInline,
  labelInline,
  textInputWarning,
  textInputInvalid,
  textInputSuccess,
  formHelperText,
  formHelperTextDisabled,
  errorText,
  formRequirement,
  textInputFieldWrapperWarning,
  textInputFieldWrapperInvalid,
  textInputFieldWrapperSuccess,
  successIcon,
  warningIcon,
  errorIcon,
  textInputCounterAlert,
  visuallyHidden,
  autofill,
};
