/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const wrapper: string;
const cardTypeIcon: string;

export {
	wrapper,
	cardTypeIcon
};

export default {
	wrapper,
	cardTypeIcon
};
