/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const suggestionList: string;
const suggestionItem: string;
const highlighted: string;

export {
	suggestionList,
	suggestionItem,
	highlighted
};

export default {
	suggestionList,
	suggestionItem,
	highlighted
};
