/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const mainContainer: string;
const content: string;
const heading: string;
const contentOnBackground: string;

export {
	mainContainer,
	content,
	heading,
	contentOnBackground
};

export default {
	mainContainer,
	content,
	heading,
	contentOnBackground
};
