/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const wrapper: string;
const flyoutPanel: string;
const header: string;
const title: string;
const content: string;
const footer: string;

export { wrapper, flyoutPanel, header, title, content, footer };

export default {
  wrapper,
  flyoutPanel,
  header,
  title,
  content,
  footer,
};
