/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const wrapper: string;
const rightToggleButton: string;
const leftToggleButton: string;
const primary: string;
const secondary: string;
const tertiary: string;
const tertiarySelected: string;
const tertiaryUnselected: string;
const primarySelected: string;
const primaryUnselected: string;
const secondarySelected: string;
const secondaryUnselected: string;
const baseToggleStyle: string;
const toggleContent: string;
const iconWrapper: string;
const labelWrapper: string;

export {
	wrapper,
	rightToggleButton,
	leftToggleButton,
	primary,
	secondary,
	tertiary,
	tertiarySelected,
	tertiaryUnselected,
	primarySelected,
	primaryUnselected,
	secondarySelected,
	secondaryUnselected,
	baseToggleStyle,
	toggleContent,
	iconWrapper,
	labelWrapper
};

export default {
	wrapper,
	rightToggleButton,
	leftToggleButton,
	primary,
	secondary,
	tertiary,
	tertiarySelected,
	tertiaryUnselected,
	primarySelected,
	primaryUnselected,
	secondarySelected,
	secondaryUnselected,
	baseToggleStyle,
	toggleContent,
	iconWrapper,
	labelWrapper
};
