/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const numberInput: string;
const label: string;
const requiredLabel: string;
const labelDisabled: string;
const formItem: string;
const numberInputWrapper: string;
const numberInputFieldOuterWrapper: string;
const numberInputFieldWrapper: string;
const numberInputLabelWrapper: string;
const numberInputLabelCounter: string;
const numberInputLabelHelperWrapper: string;
const numberInputWrapperInlineInvalid: string;
const numberInputWrapperInline: string;
const numberInputFieldOuterWrapperInline: string;
const formHelperTextInline: string;
const labelInline: string;
const numberInputWarning: string;
const numberInputInvalid: string;
const formHelperText: string;
const formHelperTextDisabled: string;
const errorNumber: string;
const formRequirement: string;
const numberInputFieldWrapperWarning: string;
const numberInputFieldWrapperInvalid: string;
const numberInputFieldWrapperSuccess: string;
const numberInputCounterAlert: string;
const visuallyHidden: string;

export {
	numberInput,
	label,
	requiredLabel,
	labelDisabled,
	formItem,
	numberInputWrapper,
	numberInputFieldOuterWrapper,
	numberInputFieldWrapper,
	numberInputLabelWrapper,
	numberInputLabelCounter,
	numberInputLabelHelperWrapper,
	numberInputWrapperInlineInvalid,
	numberInputWrapperInline,
	numberInputFieldOuterWrapperInline,
	formHelperTextInline,
	labelInline,
	numberInputWarning,
	numberInputInvalid,
	formHelperText,
	formHelperTextDisabled,
	errorNumber,
	formRequirement,
	numberInputFieldWrapperWarning,
	numberInputFieldWrapperInvalid,
	numberInputFieldWrapperSuccess,
	numberInputCounterAlert,
	visuallyHidden
};

export default {
	numberInput,
	label,
	requiredLabel,
	labelDisabled,
	formItem,
	numberInputWrapper,
	numberInputFieldOuterWrapper,
	numberInputFieldWrapper,
	numberInputLabelWrapper,
	numberInputLabelCounter,
	numberInputLabelHelperWrapper,
	numberInputWrapperInlineInvalid,
	numberInputWrapperInline,
	numberInputFieldOuterWrapperInline,
	formHelperTextInline,
	labelInline,
	numberInputWarning,
	numberInputInvalid,
	formHelperText,
	formHelperTextDisabled,
	errorNumber,
	formRequirement,
	numberInputFieldWrapperWarning,
	numberInputFieldWrapperInvalid,
	numberInputFieldWrapperSuccess,
	numberInputCounterAlert,
	visuallyHidden
};
