/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const list: string;
const listItem: string;
const innerContent: string;
const actionBarWrapper: string;
const listItemForm: string;
const listItemFormButtons: string;
const draggable: string;
const dragging: string;

export { list, listItem, innerContent, actionBarWrapper, listItemForm, listItemFormButtons, draggable, dragging };

export default {
  list,
  listItem,
  innerContent,
  actionBarWrapper,
  listItemForm,
  listItemFormButtons,
  draggable,
  dragging,
};
