/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const toastViewport: string;
const toastRoot: string;
const slideIn: string;
const hide: string;
const swipeOut: string;
const toastTitle: string;
const toastHeader: string;
const toastDescription: string;
const iconContainer: string;
const toastClose: string;
const toastLinks: string;
const toastContainer: string;
const alert: string;
const success: string;
const error: string;
const topRight: string;
const topLeft: string;
const bottomRight: string;
const bottomLeft: string;

export {
  toastViewport,
  toastRoot,
  slideIn,
  hide,
  swipeOut,
  toastTitle,
  toastHeader,
  toastDescription,
  iconContainer,
  toastClose,
  toastLinks,
  toastContainer,
  alert,
  success,
  error,
  topRight,
  topLeft,
  bottomRight,
  bottomLeft,
};

export default {
  toastViewport,
  toastRoot,
  slideIn,
  hide,
  swipeOut,
  toastTitle,
  toastHeader,
  toastDescription,
  iconContainer,
  toastClose,
  toastLinks,
  toastContainer,
  alert,
  success,
  error,
  topRight,
  topLeft,
  bottomRight,
  bottomLeft,
};
