/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const dropdownTrigger: string;
const menu: string;
const subMenu: string;
const subMenuTrigger: string;
const subMenuIcon: string;
const subMenuContent: string;
const subMenuContentRight: string;
const subMenuContentBelow: string;
const menuItem: string;
const menuItemIcon: string;
const dropdownHeader: string;
const dropdownDivider: string;

export {
  dropdownTrigger,
  menu,
  subMenu,
  subMenuTrigger,
  subMenuIcon,
  subMenuContent,
  subMenuContentRight,
  subMenuContentBelow,
  menuItem,
  menuItemIcon,
  dropdownHeader,
  dropdownDivider,
};

export default {
  dropdownTrigger,
  menu,
  subMenu,
  subMenuTrigger,
  subMenuIcon,
  subMenuContent,
  subMenuContentRight,
  subMenuContentBelow,
  menuItem,
  menuItemIcon,
  dropdownHeader,
  dropdownDivider,
};
