/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const dropZone: string;
const dragging: string;
const hiddenInput: string;

export {
	dropZone,
	dragging,
	hiddenInput
};

export default {
	dropZone,
	dragging,
	hiddenInput
};
