/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const fileUploader: string;
const fileContainer: string;
const fileDescription: string;
const fileDropContainer: string;
const disabled: string;
const left: string;
const center: string;

export { fileUploader, fileContainer, fileDescription, fileDropContainer, disabled, left, center };

export default {
  fileUploader,
  fileContainer,
  fileDescription,
  fileDropContainer,
  disabled,
  left,
  center,
};
