/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const fileUploader: string;
const fileContainer: string;
const fileDescription: string;
const fileDropContainer: string;
const disabled: string;

export {
	fileUploader,
	fileContainer,
	fileDescription,
	fileDropContainer,
	disabled
};

export default {
	fileUploader,
	fileContainer,
	fileDescription,
	fileDropContainer,
	disabled
};
