/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const fileCard: string;
const fileCardStatusIcon: string;
const cardInfoContainer: string;
const fileTypeIcon: string;
const fileTitle: string;
const fileMetaData: string;
const fileSize: string;
const fileCardProgressBarContainer: string;
const documentContainer: string;
const fileTitleContainer: string;
const menuContainer: string;
const statusIconContainer: string;
const fileStatusIcon: string;
const defaultMessageContainer: string;
const errorMessageContainer: string;
const successMessageContainer: string;
const retryButton: string;

export {
  fileCard,
  fileCardStatusIcon,
  cardInfoContainer,
  fileTypeIcon,
  fileTitle,
  fileMetaData,
  fileSize,
  fileCardProgressBarContainer,
  documentContainer,
  fileTitleContainer,
  menuContainer,
  statusIconContainer,
  fileStatusIcon,
  defaultMessageContainer,
  errorMessageContainer,
  successMessageContainer,
  retryButton,
};

export default {
  fileCard,
  fileCardStatusIcon,
  cardInfoContainer,
  fileTypeIcon,
  fileTitle,
  fileMetaData,
  fileSize,
  fileCardProgressBarContainer,
  documentContainer,
  fileTitleContainer,
  menuContainer,
  statusIconContainer,
  fileStatusIcon,
  defaultMessageContainer,
  errorMessageContainer,
  successMessageContainer,
  retryButton,
};
