/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const tabGroupContainer: string;
const tabGroup: string;
const tabHeaders: string;
const tab: string;
const activeTab: string;
const inactiveTab: string;
const tabBar: string;
const tabScroller: string;
const tabScrollerScroll: string;
const tabScrollerScrollArea: string;
const tabScrollerScrollContent: string;
const tabScrollArrows: string;
const tabList: string;
const tabContent: string;
const contentContainer: string;

export {
	tabGroupContainer,
	tabGroup,
	tabHeaders,
	tab,
	activeTab,
	inactiveTab,
	tabBar,
	tabScroller,
	tabScrollerScroll,
	tabScrollerScrollArea,
	tabScrollerScrollContent,
	tabScrollArrows,
	tabList,
	tabContent,
	contentContainer
};

export default {
	tabGroupContainer,
	tabGroup,
	tabHeaders,
	tab,
	activeTab,
	inactiveTab,
	tabBar,
	tabScroller,
	tabScrollerScroll,
	tabScrollerScrollArea,
	tabScrollerScrollContent,
	tabScrollArrows,
	tabList,
	tabContent,
	contentContainer
};
