/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const iconButton: string;
const small: string;
const medium: string;
const large: string;
const none: string;
const outline: string;
const filled: string;
const square: string;
const bevel: string;
const round: string;
const base: string;
const primary: string;
const secondary: string;
const tertiary: string;

export {
	iconButton,
	small,
	medium,
	large,
	none,
	outline,
	filled,
	square,
	bevel,
	round,
	base,
	primary,
	secondary,
	tertiary
};

export default {
	iconButton,
	small,
	medium,
	large,
	none,
	outline,
	filled,
	square,
	bevel,
	round,
	base,
	primary,
	secondary,
	tertiary
};
