/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const progressBarContainer: string;
const progressBar: string;
const progressBarTextContainer: string;
const primary: string;
const secondary: string;
const info: string;
const xs: string;
const sm: string;
const md: string;
const lg: string;
const animatedBase: string;
const shine: string;
const nonAnimatedBase: string;
const indeterminateProgress: string;

export {
  progressBarContainer,
  progressBar,
  progressBarTextContainer,
  primary,
  secondary,
  info,
  xs,
  sm,
  md,
  lg,
  animatedBase,
  shine,
  nonAnimatedBase,
  indeterminateProgress,
};

export default {
  progressBarContainer,
  progressBar,
  progressBarTextContainer,
  primary,
  secondary,
  info,
  xs,
  sm,
  md,
  lg,
  animatedBase,
  shine,
  nonAnimatedBase,
  indeterminateProgress,
};
