/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const nav: string;
const navLogo: string;
const navLinks: string;
const additionalContentContainer: string;
const activeLink: string;
const navAvatar: string;
const avatarTrigger: string;
const logoutButtonWrapper: string;
const alertContainer: string;
const alertBadge: string;

export {
	nav,
	navLogo,
	navLinks,
	additionalContentContainer,
	activeLink,
	navAvatar,
	avatarTrigger,
	logoutButtonWrapper,
	alertContainer,
	alertBadge
};

export default {
	nav,
	navLogo,
	navLinks,
	additionalContentContainer,
	activeLink,
	navAvatar,
	avatarTrigger,
	logoutButtonWrapper,
	alertContainer,
	alertBadge
};
