/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const sizeSmall: string;
const illustration: string;
const sizeMedium: string;
const sizeLarge: string;
const centered: string;
const titleWrapper: string;
const actionButtons: string;
const content: string;
const titleSection: string;
const titleIcon: string;

export {
	container,
	sizeSmall,
	illustration,
	sizeMedium,
	sizeLarge,
	centered,
	titleWrapper,
	actionButtons,
	content,
	titleSection,
	titleIcon
};

export default {
	container,
	sizeSmall,
	illustration,
	sizeMedium,
	sizeLarge,
	centered,
	titleWrapper,
	actionButtons,
	content,
	titleSection,
	titleIcon
};
