/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const sidebar: string;
const collapsed: string;
const base: string;
const compact: string;
const minimal: string;
const sidebarHeader: string;
const brand: string;
const logoContainer: string;
const logoButton: string;
const sectionHeader: string;
const sectionContent: string;
const sidebarContent: string;
const sidebarNav: string;
const navSection: string;
const sidebarSection: string;
const sectionTitle: string;
const navButton: string;
const active: string;
const disabled: string;
const iconButton: string;
const navLabel: string;
const navBadge: string;
const sidebarFooter: string;
const cancelIcon: string;

export {
  sidebar,
  collapsed,
  base,
  compact,
  minimal,
  sidebarHeader,
  brand,
  logoContainer,
  logoButton,
  sectionHeader,
  sectionContent,
  sidebarContent,
  sidebarNav,
  navSection,
  sidebarSection,
  sectionTitle,
  navButton,
  active,
  disabled,
  iconButton,
  navLabel,
  navBadge,
  sidebarFooter,
  cancelIcon,
};

export default {
  sidebar,
  collapsed,
  base,
  compact,
  minimal,
  sidebarHeader,
  brand,
  logoContainer,
  logoButton,
  sectionHeader,
  sectionContent,
  sidebarContent,
  sidebarNav,
  navSection,
  sidebarSection,
  sectionTitle,
  navButton,
  active,
  disabled,
  iconButton,
  navLabel,
  navBadge,
  sidebarFooter,
  cancelIcon,
};
