/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const card: string;
const base: string;
const bordered: string;
const divider: string;
const cardLoading: string;
const loadingOverlay: string;
const cardTitle: string;
const cardContent: string;
const cardFooter: string;
const footerStart: string;
const footerCenter: string;
const footerEnd: string;

export {
  card,
  base,
  bordered,
  divider,
  cardLoading,
  loadingOverlay,
  cardTitle,
  cardContent,
  cardFooter,
  footerStart,
  footerCenter,
  footerEnd,
};

export default {
  card,
  base,
  bordered,
  divider,
  cardLoading,
  loadingOverlay,
  cardTitle,
  cardContent,
  cardFooter,
  footerStart,
  footerCenter,
  footerEnd,
};
