/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const breadcrumb: string;
const breadcrumbItem: string;
const current: string;
const link: string;
const noTrailingSlash: string;

export {
	breadcrumb,
	breadcrumbItem,
	current,
	link,
	noTrailingSlash
};

export default {
	breadcrumb,
	breadcrumbItem,
	current,
	link,
	noTrailingSlash
};
