/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const mainWrapper: string;
const focused: string;
const promptContainer: string;
const innerElements: string;
const textArea: string;
const iconSlot: string;
const fileSlot: string;
const promptFooter: string;
const slotWrapper: string;
const leftSlot: string;
const rightSlot: string;
const bottomSlot: string;
const srOnly: string;

export {
  mainWrapper,
  focused,
  promptContainer,
  innerElements,
  textArea,
  iconSlot,
  fileSlot,
  promptFooter,
  slotWrapper,
  leftSlot,
  rightSlot,
  bottomSlot,
  srOnly,
};

export default {
  mainWrapper,
  focused,
  promptContainer,
  innerElements,
  textArea,
  iconSlot,
  fileSlot,
  promptFooter,
  slotWrapper,
  leftSlot,
  rightSlot,
  bottomSlot,
  srOnly,
};
