/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const footer: string;
const footerLinks: string;
const footerList: string;
const footerLink: string;
const LogoSection: string;
const appSection: string;
const contactSection: string;
const copyrightSection: string;
const footerIcons: string;
const socialLinks: string;

export {
  footer,
  footerLinks,
  footerList,
  footerLink,
  LogoSection as logoSection,
  appSection,
  contactSection,
  copyrightSection,
  footerIcons,
  socialLinks,
};

export default {
  footer,
  footerLinks,
  footerList,
  footerLink,
  logoSection: LogoSection,
  appSection,
  contactSection,
  copyrightSection,
  footerIcons,
  socialLinks,
};
