/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const text: string;
const xs: string;
const small: string;
const body: string;
const large: string;
const xl: string;
const h1: string;
const h2: string;
const h3: string;
const h4: string;
const h5: string;
const h6: string;
const a: string;
const light: string;
const normal: string;
const medium: string;
const bold: string;
const base: string;
const neutral80: string;
const neutral60: string;
const disabled: string;
const primary: string;
const secondary: string;
const tertiary: string;
const accent: string;
const help: string;
const info: string;
const success: string;
const warning: string;
const error: string;

export {
  text,
  xs,
  small,
  body,
  large,
  xl,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  a,
  light,
  normal,
  medium,
  bold,
  base,
  neutral80,
  neutral60,
  disabled,
  primary,
  secondary,
  tertiary,
  accent,
  help,
  info,
  success,
  warning,
  error,
};

export default {
  text,
  xs,
  small,
  body,
  large,
  xl,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  a,
  light,
  normal,
  medium,
  bold,
  base,
  neutral80,
  neutral60,
  disabled,
  primary,
  secondary,
  tertiary,
  accent,
  help,
  info,
  success,
  warning,
  error,
};
