/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const split: string;
const wrapper: string;
const iconWrapper: string;
const headingWrapper: string;
const inlineHeading: string;
const label: string;
const splitTrigger: string;
const small: string;
const medium: string;
const large: string;
const disabled: string;
const base: string;
const primary: string;
const secondary: string;
const tertiary: string;

export {
  split,
  wrapper,
  iconWrapper,
  headingWrapper,
  inlineHeading,
  label,
  splitTrigger,
  small,
  medium,
  large,
  disabled,
  base,
  primary,
  secondary,
  tertiary,
};

export default {
  split,
  wrapper,
  iconWrapper,
  headingWrapper,
  inlineHeading,
  label,
  splitTrigger,
  small,
  medium,
  large,
  disabled,
  base,
  primary,
  secondary,
  tertiary,
};
