/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const searchInput: string;
const search: string;
const searchDisabled: string;
const label: string;
const visuallyHidden: string;
const searchButton: string;
const searchClose: string;
const searchCloseHidden: string;
const searchOuterWrapper: string;
const searchCollapsed: string;
const searchExpanded: string;
const searchIcon: string;

export {
	searchInput,
	search,
	searchDisabled,
	label,
	visuallyHidden,
	searchButton,
	searchClose,
	searchCloseHidden,
	searchOuterWrapper,
	searchCollapsed,
	searchExpanded,
	searchIcon
};

export default {
	searchInput,
	search,
	searchDisabled,
	label,
	visuallyHidden,
	searchButton,
	searchClose,
	searchCloseHidden,
	searchOuterWrapper,
	searchCollapsed,
	searchExpanded,
	searchIcon
};
