/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const link: string;
const sm: string;
const md: string;
const lg: string;
const visited: string;

export {
	link,
	sm,
	md,
	lg,
	visited
};

export default {
	link,
	sm,
	md,
	lg,
	visited
};
